@baseUrl = http://localhost:8000/api

### 1. Регистрация пользователя
POST {{baseUrl}}/users/register
Content-Type: application/json

{
  "name": "Иван Иванов",
  "email": "ivan@example.com",
  "password": "password123",
  "role": "STUDENT"
}

> {%
    client.global.set("userId", response.body.id);
%}

### 2. Вход (Login)
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "ivan@example.com",
  "password": "password123"
}

### 3. Получение профиля текущего пользователя (/me доступен всем)
GET {{baseUrl}}/users/me

### 4. Обновление профиля текущего пользователя (/me)
PATCH {{baseUrl}}/users/me
Content-Type: application/json

{
  "name": "Иван Петров"
}

### 5. Попытка получить профиль по ID обычным пользователем (Ожидается 403 Forbidden)
GET {{baseUrl}}/users/{{userId}}

### 6. Обновление токенов (Refresh)
POST {{baseUrl}}/auth/refresh

### 7. Смена пароля текущего пользователя (/me)
POST {{baseUrl}}/users/me/change-password
Content-Type: application/json

{
  "old_password": "password123",
  "new_password": "newpassword123"
}

### 8. Выход из системы (Logout)
POST {{baseUrl}}/auth/logout

### 9. Завершение всех сессий текущего пользователя (Auth /me)
POST {{baseUrl}}/auth/logout-all/me


### 10. Запрос токена восстановления пароля
POST {{baseUrl}}/recovery
Content-Type: application/json

{
  "email": "ivan@example.com"
}

> {%
    client.global.set("recoveryToken", response.body.token);
%}

### 11. Проверка токена восстановления
GET {{baseUrl}}/recovery/{{recoveryToken}}

### 12. Сброс пароля по токену восстановления
POST {{baseUrl}}/recovery/reset-password
Content-Type: application/json

{
  "token": "{{recoveryToken}}",
  "new_password": "newSecurePassword456"
}

### 13. Удаление собственного профиля (/me)
DELETE {{baseUrl}}/users/me
